# Generated by Django 5.2.1 on 2025-05-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_tokens_delete_usertokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(max_length=6),
        ),
    ]
