# Generated by Django 5.2.1 on 2025-05-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_tokens_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokens',
            options={'ordering': ('-created_at',), 'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
    ]
