# Generated by Django 5.2.1 on 2025-06-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='image_url',
            new_name='thumbnail',
        ),
    ]
