# Generated by Django 5.2.1 on 2025-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_rename_image_url_content_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration in seconds', max_length=255, null=True),
        ),
    ]
