# Generated by Django 5.2.1 on 2025-06-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_content_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
    ]
