# Generated by Django 5.2.1 on 2025-06-30 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_content_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_playing', models.BooleanField(default=False)),
                ('current_time', models.IntegerField(default=0, help_text='Current playback time in seconds')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='room.room')),
            ],
        ),
    ]
